# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Required
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Install with pip using pyproject.toml
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
