# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Include all submodules
submodules:
  include: all

# Required
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - rm -rf docs/_build

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Install with pip using pyproject.toml
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
